### ISSUE TITLE
Input Data of 2022 Wang Biogeoscience

### ISSUE THREAD

**Issue by kongdd** [Yujie-WANG/Published-Codes-Yujie-WANG#1]
Dear @Yujie-W 

Could you give the input data of 2022 Wang Biogeoscience.
<[2022 Wang Biogeoscience](https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG/blob/master/2022-Wang-Biogeosciences-Impact/src/general/query_data.jl#L44)>
I am very interested about the `Land.jl`. Thank you for making them public available.

Cheers,
Dongdong

**Comment by Yujie-W** [comment]
If you run this Julia function, it will download data automatically. If you need it for other programming languages, you may downloaded it manually using the [Artifacts.toml](https://github.com/Yujie-WANG/Published-Codes-Yujie-WANG/blob/master/2022-Wang-Biogeosciences-Impact/Artifacts.toml) file.
BTW, I am not supposed to share the raw data from the flux towers, you need to download those from AmeriFlux.

**Comment by kongdd** [comment]
Thanks for your help.
Thanks for your great work!

**Comment by kongdd** [comment]
Thank you @Yujie-W.

I am planing to use Land.jl to simulate global ET (0.5°, daily scale, 20 year). 
Do you think how long it will be taken in a normal PC?

**Comment by Yujie-W** [comment]
You need hourly simulation to get daily ET sum, and it will take about 240 * 4 * 3 hours = 2880 hours = 120 days on a single core for simulations only.

**Comment by kongdd** [comment]
Thanks for your guidance. 
Hope have the opportunity to cooperation.
